#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0

import argparse

import record
import report
import schemes

class SubCmdHelpFormatter(argparse.RawDescriptionHelpFormatter):
    def _format_action(self, action):
        parts = super(argparse.RawDescriptionHelpFormatter,
                self)._format_action(action)
        # skip sub parsers help
        if action.nargs == argparse.PARSER:
            parts = '\n'.join(parts.split('\n')[1:])
        return parts

parser = argparse.ArgumentParser(formatter_class=SubCmdHelpFormatter)

subparser = parser.add_subparsers(title='command', dest='command',
        metavar='<command>')
subparser.required = True

parser_record = subparser.add_parser('record',
        help='record data accesses of the given target processes')
record.set_argparser(parser_record)

parser_schemes = subparser.add_parser('schemes',
        help='apply operation schemes to the given target process')
schemes.set_argparser(parser_schemes)

parser_report = subparser.add_parser('report',
        help='report the recorded data accesses in the specified form')
report.set_argparser(parser_report)

args = parser.parse_args()

if args.command == 'record':
    record.main(args)
elif args.command == 'schemes':
    schemes.main(args)
elif args.command == 'report':
    report.main(args)
